# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TCAT' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TCAT

  target 'TCATTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TCATUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
